### PR TITLE
Property injection in constructor

### PR DESCRIPTION
**Pull request by matjaz**
This is something I am ready to release as version 1.0 if you're ok with it.

If yes, let's create an org. and I'll add you as an maintainer of the npm package.

br

### CODE REVIEW

**Comment by heruan** [comment]
Thank you @matjaz! Can you explain the changes of this PR one by one? I'd like to document it well.

**Comment by matjaz** [comment]
Hey,

I think this are the main changes:
- extracted `injectFn` for reusage in other decorators
- removed `undefined` comparison (we can check falsy values)
- renamed `InvocationHandlerWrapper` to `InvocationHandler` and removed export in index (not needed)
- in `configure` make a decision if we really need new `InvocationHandler`, otherwise return original one
- in `InvocationHandler` create object using `Object.create`, allowing us to pass properties before constructor is called (removed afterConstructor (not needed))
- unit tests converted to TypeScript
- added autoinject & configure tests

**Comment by heruan** [comment]
Great! Would you report a simple performance test between the current plugin and your PR to see if using `Object.create` is a plus/plus rather than a plus/minus? In the meantime I'll create the org and prepare the migration!

**Comment by matjaz** [comment]
Here are some results from simple test


Test case:
```javascript
fdescribe('perf', () => {
    it('test', () => {
        const COUNT = 99999

        @transient('x')
        class App {}
        // comment this out to test non property injected classes
        App.injectProperties = {}

        const container = getContainer()
        console.time('t1')
        for (var i=0; i<COUNT; i++) {
            container.get(App)
        }
        console.timeEnd('t1')
    })
})
```

Results:

Type | without injectProperties (ms) | using injectProperties (ms)
------------ | ------------- | -------
Current master | 91 | 105
PR | 69 | 150

It's expected `Object.create` is slower than `new Fn` since it allows more flexibility.
It's interesting to see mine PR is faster for classes without `injectProperties` (not creating new `InvocationHandler`).
I think props in constructor is a big plus for code maintainability so if performance is really a concern we could add configuration which strategy to use.
What do you think?

**Comment by matjaz** [comment]
I've added plugin `injectConstructor` config. Also added TypeScript code coverage.

**Comment by heruan** [comment]
Thank you @matjaz I was oot the last few days, I'll check it out asap and merge.

**Comment by heruan** [comment]
Merged and moved to a new org, you should have received the invite! I'm already updated the README to point to the NPM installation, please publish version 0.4.0 there and possibly add me as maintainer. Thank you for you help, I look forward to keep this repo updated together and collaborate on other projects too!

**Comment by matjaz** [comment]
Published 0.4 version and added you as collaborator. 👍

**Pull request merged**
